Clean up migrations to work on an empty environment
voorhoede/head-start pull request #163
Opened 2024-08-05 08:53 UTC by Siilwyn

Closes #62

Chose to add a package.json commonjs boundary to dato so we can keep module in root.
Tested by creating a new dato project and using `datocms migrations:run`.

2024-08-05 08:55 UTC, Siilwyn commented on package.json
> +    "@datocms/cli": "^2.0.5",
Updated the CLI, because why not, seems to work.

2024-08-06 09:54 UTC, decrek reviewed
In the readme there are warnings about this issue an d the seed script: https://github.com/voorhoede/head-start/blob/migrations-iteration/docs/getting-started.md#create-a-datocms-project. Can you update this section based on your changes?

2024-08-06 10:19 UTC, decrek requested changes
Looks really good! Just some documentation updates and I'm happy!

2024-08-22 10:23 UTC, Siilwyn commented on docs/getting-started.md
> +```shell
Replace syntax highlighting language `bash` alias with more appropriate/generic `shell`.

2024-08-22 10:24 UTC, Siilwyn commented on docs/getting-started.md
> +```dotenv
Fix syntax highlighting, this isn't bash.

2024-08-22 10:26 UTC, Siilwyn commented on docs/getting-started.md
> -- [Create a new DatoCMS project](https://dashboard.datocms.com/personal-account/projects/browse/new) (select blank project).
This URL doesn't work for me, simplified the step description a bit.

2024-08-22 13:17 UTC, jbmoelker approved these changes
Works like a charm! Tested it with a blank DatoCMS project. All the migrations run successfully. Schema looks good.

Only suggestions:
- document the `"type": "commonjs"` in `config/datocms/package.json`?
- create a new issue to rebuild head-start datocms instance with these migrations and (manually) copy all the content?

2024-08-22 13:18 UTC, merged