feat: proxy files with custom slugs (WIP)
voorhoede/head-start pull request #224
Opened 2024-12-07 09:45 UTC by jbmoelker

# To do

- Reimplement slug on model
- Use getSlug from file.ts
- Add demo

# Changes

# Associated issue

Resolves #155

# How to test

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have made sure that my PR is easy to review (not too big, includes comments)
- [ ] I have made updated relevant documentation files (in project README, docs/, etc)
- [ ] I have added a decision log entry if the change affects the architecture or changes a significant technology
- [ ] I have notified a reviewer

2024-12-23 13:18 UTC, jbmoelker commented on src/lib/routing/FileRoute.fragment.graphql
> +  customSlug: slug
required to resolve clashing types with other `slug` fields on route fragments

2024-12-23 13:19 UTC, jbmoelker commented on src/middleware/proxy-files.ts
> +import { defineMiddleware } from 'astro/middleware';
Using the new atomic middleware handlers setup introduced in #222

2025-01-06 10:17 UTC, jurgenbelien requested changes

2025-01-06 10:17 UTC, jurgenbelien commented on config/datocms/migrations/1734959319_customFileSlugs.ts
> +    api_key: 'slug',
I think naming this slug is confusing. In my perception, a *slug* is a human-readable, yet machine-safe path *fragment*. What is described in the hint, and in the `customFields` function seems to show a *path*, not a *slug*

2025-01-06 10:17 UTC, jurgenbelien commented on scripts/download-file-proxy-map.ts
> +  const fileSlugMap = {} as FileSlugMap;
```suggestion
  const fileSlugMap: FileSlugMap = {};
```

This is safer than `as`:

<img width="330" alt="image" src="https://github.com/user-attachments/assets/9ae66cab-6a07-4ea7-91fd-099b7ea35a3a" />

2025-01-06 10:17 UTC, jurgenbelien commented on src/lib/routing/FileRoute.fragment.graphql
> +  customSlug: slug
This would also be resolved when renaming the field

2025-03-03 15:45 UTC, jurgenbelien approved these changes
Changed `slug` to `path`

2025-03-03 15:51 UTC, merged