feat(AppMenu): basic editable responsive menu
voorhoede/head-start pull request #230
Opened 2024-12-20 17:07 UTC by jbmoelker

# Changes

Note: other types of menu items (like external links) and nested menu items can be added in a separate PR so this one doesn't become to big.

# Associated issue

Part of #196.

# How to test

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have made sure that my PR is easy to review (not too big, includes comments) (only `AppMenu` is really new, other files are moved around and many short `README`s are added)
- [x] I have made updated relevant documentation files (in project README, docs/, etc)
- ~I have added a decision log entry if the change affects the architecture or changes a significant technology~
- [x] I have notified a reviewer

2024-12-28 22:07 UTC, jbmoelker commented on src/components/UnstyledList/README.md
> +Lists require `[role="list"]` attribute when `list-style: none;` is applied to maintain accessibility in VoiceOver in Safari. See [explanation on web.dev](https://web.dev/articles/website-navigation#
Better reference? https://developer.mozilla.org/en-US/docs/Web/CSS/list-style#accessibility

2025-01-06 09:37 UTC, jurgenbelien requested changes
I feel that the close behavior of the menu dialog is a bit to eager in closing itself.

2025-01-06 09:37 UTC, jurgenbelien commented on src/components/UnstyledList/README.md
> +Lists require `[role="list"]` attribute when `list-style: none;` is applied to maintain accessibility in VoiceOver in Safari. See [explanation on web.dev](https://web.dev/articles/website-navigation#
MDN's wording is a bit vague but this is only the case for lists outside of `<nav>`. Not saying that we shouldn't add role="list"regardless, just wanted to clarify.

<img width="674" alt="image" src="https://github.com/user-attachments/assets/39d1e7d9-36d9-489d-9c02-d523f0ce2ca9" />

2025-01-06 09:37 UTC, jurgenbelien commented on src/layouts/AppMenu/AppMenu.astro
> +  <dialog data-menu-dialog>
No popover API? 😅

2025-01-06 09:37 UTC, jurgenbelien commented on src/layouts/AppMenu/AppMenuItem.astro
> +  item: AppMenuFragment['menuItems'][0];
```suggestion
  item: AppMenuFragment['menuItems'][number];
```
This does not have an impact in this case, but there might be situations where an array is interpreted as a tuple by Typescript, and if this pattern is repeated in that instance you would have incorrect types.

2025-01-06 09:37 UTC, jurgenbelien commented on src/layouts/AppMenu/AppMenu.client.ts
> +    this.#dialog.addEventListener('click', this.close.bind(this));
I find this behavior a bit weird. Clicking anywhere except the links in the dialog will close the menu dialog. What if I want to copy some text from the menu dialog? That would be impossible at the moment, because the dialog is dismissed the moment I release my mouse/trackpad button. I would expect the close handler to be only on the backdrop and the close button.

2025-01-06 16:15 UTC, jbmoelker commented on config/datocms/migrations/1706210000_translations.ts
> +    'close_menu': 'close menu',
I think we should use seeds for this. See #27 . But this is the best we have for now for new projects using Head Start.

2025-01-06 16:17 UTC, jbmoelker commented on src/layouts/AppMenu/AppMenu.astro
> +  <dialog data-menu-dialog>
No, that would open as `.show()` instead of `.showModal()`. So can't use popover API :-/

2025-01-06 16:18 UTC, jbmoelker commented on src/layouts/AppMenu/AppMenu.client.ts
> +    this.#dialog.addEventListener('click', this.close.bind(this));
Will do.

2025-01-06 16:19 UTC, jbmoelker commented on src/components/UnstyledList/README.md
> +Lists require `[role="list"]` attribute when `list-style: none;` is applied to maintain accessibility in VoiceOver in Safari. See [explanation on web.dev](https://web.dev/articles/website-navigation#
So developers can decide when to use this UnstyledList component.

2025-01-06 17:16 UTC, jbmoelker commented on src/layouts/AppMenu/AppMenu.client.ts
> +    this.#dialog.addEventListener('click', this.close.bind(this));
Resolved with separate event listener for close button and check if click is outside the dialog.

2025-01-07 06:52 UTC, jurgenbelien approved these changes

2025-01-07 06:52 UTC, jurgenbelien commented on src/layouts/AppMenu/AppMenu.client.ts
> +      event.clientX > rect.right;
nice

2025-01-07 08:21 UTC, merged